version: "3.2"

networks:
    logging:
        driver: overlay
        attachable: true

services:
    logstash:
        build: logstash/
        image: lancekuo/logstash:6.2.3
        ports:
            - 4790:4790/udp
        networks:
            - logging
        environment:
            DEBUG:                  "${LOGSTASH_DEBUG:-false}"
            LOGSPOUT:               ignore
            ELASTICSEARCH_USER:     ${ELASTICSEARCH_LOGS_USER}
            ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_LOGS_PASSWORD}
            ELASTICSEARCH_SSL:      ${ELASTICSEARCH_LOGS_SSL}
            ELASTICSEARCH_ADDR:     ${ELASTICSEARCH_LOGS_ADDR:-elasticsearch}
            ELASTICSEARCH_PORT:     ${ELASTICSEARCH_LOGS_PORT:-9200}
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 300M

    elasticsearch:
        build: elasticsearch/
        image: lancekuo/elasticsearch:6.2.3
        ports:
            - 9200:9200
        networks:
            - logging
        environment:
            - LOGSPOUT=ignore
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - 'ES_JAVA_OPTS=-Xms512m -Xmx2048m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 2048M
                reservations:
                    cpus: '0.5'
                    memory: 512M

    kibana:
        build: kibana/
        image: lancekuo/kibana:6.2.3
        ports:
            - "5601:5601"
        environment:
            - LOGSPOUT=ignore
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 2048M
                reservations:
                    cpus: '0.5'
                    memory: 512M
