version: "3.5"

networks:
    app-network:
        external: true
        name: app-network
    log-network:
        external: true
        name: log-network

services:
    logstash:
        build: logstash/
        image: lancekuo/logstash:6.3.2-2
        ports:
            - 4790:4790/udp
            - 4790:4790
        networks:
            - log-network
            - app-network
        environment:
            - LOG_LEVEL=warn # fatal error warn info debug trace
            - ELASTICSEARCH_USER=${ELASTICSEARCH_LOGS_USER}
            - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_LOGS_PASSWORD}
            - ELASTICSEARCH_SSL=${ELASTICSEARCH_LOGS_SSL}
            - ELASTICSEARCH_ADDR=${ELASTICSEARCH_LOGS_ADDR:-elasticsearch}
            - ELASTICSEARCH_PORT=${ELASTICSEARCH_LOGS_PORT:-9200}
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 300M
    elasticsearch:
#   sudo sysctl -w vm.max_map_count=262144 # For Linux
        build: elasticsearch/
        image: lancekuo/elasticsearch:6.3.2
        networks:
            - log-network
        environment:
            - bootstrap.memory_lock=true
            - cluster.name=${CLUSTER_NAME:-development}
            - discovery.type=zen
            - discovery.zen.minimum_master_nodes=2
            - discovery.zen.ping.unicast.hosts=elasticsearch
            - network.host=_eth0_
            - 'ES_JAVA_OPTS=-Xms3g -Xmx3g'
#            - path.data=/data/$${HOSTNAME}
#        volumes:
#            - data:/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 3G
                reservations:
                    cpus: '0.5'
                    memory: 3G

    kibana:
        build: kibana/
        image: lancekuo/kibana:6.3.2
        networks:
            - log-network
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - LOGGING_QUIET=true
            - SERVER_HOST=0.0.0.0
            - SERVER_NAME=${CLUSTER_NAME:-development}
            - XPACK_GRAPH.ENABLED=false
            - XPACK_ML_ENABLED=false
            - XPACK_MONITORING_ENABLED=false
            - XPACK_REPORTING_ENABLED=false
            - XPACK_SECURITY_ENABLED=false
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 2048M
                reservations:
                    cpus: '0.5'
                    memory: 512M
