version: "3.5"

networks:
    app-network:
        external: true
        name: app-network
    log-network:
        external: true
        name: log-network

services:
    logstash:
        build: logstash/
        image: lancekuo/logstash:6.2.3
        ports:
            - 4790:4790/udp
            - 4790:4790
        networks:
            - log-network
            - app-network
        environment:
            - LOG_LEVEL=warn # fatal error warn info debug trace
            - ELASTICSEARCH_USER=${ELASTICSEARCH_LOGS_USER}
            - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_LOGS_PASSWORD}
            - ELASTICSEARCH_SSL=${ELASTICSEARCH_LOGS_SSL}
            - ELASTICSEARCH_ADDR=${ELASTICSEARCH_LOGS_ADDR:-elasticsearch}
            - ELASTICSEARCH_PORT=${ELASTICSEARCH_LOGS_PORT:-9200}
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 300M

    elasticsearch:
        build: elasticsearch/
        image: lancekuo/elasticsearch:6.2.3
        ports:
            - 9200:9200
        networks:
            - log-network
        environment:
            - cluster.name=docker-cluster
            - http.host=0.0.0.0
            - network.host=localhost
            - path.data=/opt/elasticsearch
#            - bootstrap.memory_lock=true # TODO find the solution to this
            - xpack.security.enabled=false
            - 'ES_JAVA_OPTS=-Xms1g -Xmx2g'
        volumes:
            - "/opt/elasticsearch:/opt/elasticsearch"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        deploy:
            placement:
                constraints:
                    - node.labels.type == storage
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 2G
                reservations:
                    cpus: '0.5'
                    memory: 2G

    kibana:
        build: kibana/
        image: lancekuo/kibana:6.2.3
        networks:
            - log-network
        ports:
            - "5601:5601"
        environment:
            - LOGGING_QUIET=true
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        deploy:
            placement:
                constraints:
                    - node.labels.type == internal
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '1'
                    memory: 2048M
                reservations:
                    cpus: '0.5'
                    memory: 512M
